config/routes.rb
Rails.application.routes.draw do
  root to: "customers#index"
  get "customers/missing_email"
  get "customers/alphabetized"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one_attached :image

  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.all.order("full_name")
  end

  def missing_email
    @customers = Customer.all.where("email_address = ''")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
  <aside>
    <h2><strong><%= customer.full_name %></strong></h2>
    <% if customer.image.present? %>
      <p><%= image_tag customer.image.variant(resize_to_limit: [285, 285]).processed  %></p>
    <% end %>
    <p><strong>Notes: </strong><%= customer.notes %></p>
    <p><%= customer.phone_number %></p>
    <p><%= customer.email_address %></p>
  </aside>

app/views/customers/alphabetized.html.erb
<h1>All Customers ordered by full name</h1>
<section>
  <%= render @customers %>
</section>
<nav>
  <ul>
    <li><%= link_to 'All customers', root_path %></li>
    <li><%= link_to 'Customers with missing email', customers_missing_email_path %></li>
  </ul>
</nav>

app/views/customers/index.html.erb
<h1>All Customers</h1>
<section>
  <%= render @customers %>
</section>
<nav>
  <ul>
    <li><%= link_to 'Customers with missing email', customers_missing_email_path %></li>
    <li><%= link_to 'All customers alphabetized', customers_alphabetized_path %></li>
  </ul>
</nav>

app/views/customers/missing_email.html.erb
<h1>All Customers missing email address</h1>
<section>
  <%= render @customers %>
</section>
<nav>
  <ul>
    <li><%= link_to 'All customers', root_path %></li>
    <li><%= link_to 'All customers alphabetized', customers_alphabetized_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://unpkg.com/mvp.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>